version: '3.7'
services:

  my-favorite-artist:
    image: my-favorite-artist
    container_name: my-favorite-artist-altrimetrix
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CONFIG_PATH=config/local
    ports:
#       REST server
      - "8090:8080"
    networks:
      - mp
networks:
  mp:
    driver: bridge